---
title: "Data Cleaning per la Ricerca Clinica"
subtitle: "Clinical Research Academy"
author: "[CorradoLanera](www.CorradoLanera.it)"
date: "2021-10-13 (last update: `r Sys.Date()`)"
output: 
  xaringan::moon_reader:
    seal: false  # no title slide! Do It Yourself
    nature:
      highlightStyle: github
      highlightLines: true
    css: xaringan-themer.css
---
name: tidy-intro
class: inverse, middle, center

# Tidy data

### XXXX



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.retina = 3,
  warning = FALSE,
  message = FALSE,
  comment = ""
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
red <- "#f34213"
purple <- "#3e2f5b"
orange <- "#ff8811"
green <- "#136f63"
white <- "#FFFFFF"

pastel_orange <- "#F97B64"
blu_gray <- "#1F4257"

style_duo_accent(
    # primary_color = pastel_orange
    # secondary_color = purple,
    colors = c(
        red = red,
        purple = purple,
        orange = orange,
        green = green,
        white = white,
        pastel_orange = pastel_orange,
        blu_gray = blu_gray
    )
)
```

```{r xaringanExtra, include=FALSE}
xaringanExtra::use_xaringan_extra(c(
  "tileview",
  "animate_css",
  "tachyons",
  "editable",
  "panelset",
  "webcam",
  "clipboard",
  "freezeframe",
  "share_again"
))
```

```{r countdown, echo = FALSE, include = FALSE}
library(countdown)
# countdown(minutes = 0, seconds = 15)
```

---

---

name: me
class: center middle inverse


# Vediamolo da vivo!

< script >

---

name: you
class: center middle inverse

# Tocca a te

< quiz >

.right[
```{r, echo = FALSE}
countdown(minutes = 1, seconds = 0)
```
]



---
name: tidy-next
class: inverse, middle, center

# Tidy data

### Fine.

### Prossimo argomento: [numeri](06-numeri.html) 
